### ISSUE TITLE
Readme.md

### ISSUE THREAD

**Issue by LukvonStrom** [J0ker98/MySQLCommands#2]
Installation Tutorial is outdated

**Comment by J0ker98** [comment]
I'll update it tomorrow since today is my B'Day :P (I also have in mind lots of updates and integrations in mind that I'll release completly tomorrow)

**Comment by J0ker98** [comment]
Also, you are now an official Contributor of this repo ;)

**Comment by LukvonStrom** [comment]
Okay I'll change it. Happy Birthday ! :)
