### ISSUE TITLE
Some thoughts...

### ISSUE THREAD

**Issue by LukvonStrom** [J0ker98/MySQLCommands#4]
With the new update the project is using the old deprecated mysql function again. Using  mysqli or pdo  may be a good idea. I can implement it again if you want. And a thought of mine was to implement a delimiter so multiple commands could be send at once and the script would split them in multiple mysql inserts

**Comment by J0ker98** [comment]
I bringed back the old mysql function because the mysqli code you used wasn't working... You can implement it but test it before uploading it here (there is some mysql in the index too for the schedule) ;)

**Comment by LukvonStrom** [comment]
#edited

**Comment by J0ker98** [comment]
If you have time to do so, go on... Just use the same MessageHandler function I've been using (take a look at it in execute.php, it's simple)

**Comment by J0ker98** [comment]
Keep in mind to test everything before uploading it here

**Comment by LukvonStrom** [comment]
so I´ll try to merge the optimisations and the login script in 1 big update which I´ll in the next 2-3 weeks

**Comment by LukvonStrom** [comment]
So what do you think about adding as a second method a mcjsonapi integration? http://mcjsonapi.com/

**Comment by J0ker98** [comment]
hmmm this would require a different scripting concept because we would need to rewrite the scripts so the user can choose if use jsonapi or mysqlcommands... I could check this jsonapi thing when I have time but it will be likely the next weekend when I have some spare time, but that's a possibility! Maybe we could work out a complete Minecraft managing console ;)

**Comment by LukvonStrom** [comment]
About Choosing: The best option is maybe to provide the scripts for each method in a folder in the repository. I thought about writing a complete console that may be cool but requires much time and very clean code so for now I think the possibility to choose between 2 Methods is enough for now. If one of us has more free time we could add a seperate branch for that.

**Comment by J0ker98** [comment]
I'm completly with it, that was how I was thinking it... It could work like that the index, when you firstly install the tool tell you the installation instructions and pros and cons about jsonapi and mysqlcommands, then you go to the config file, choose the method you wanna use and then the index adapt itself to the method you are using... I think that jsonapi could have not just a command prompt but some other cool stuff like server's tps and other fancy things

**Comment by LukvonStrom** [comment]
Invited you to my slack team. Discussing is easier by using that instead of the issue management
